{% set version = "0.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-listarrays
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/listarrays_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/listarrays/listarrays_{{ version }}.tar.gz
  sha256: 568308220ff2f7cfccf2373cb38d51c4a73faa071d2a6265d627e7c878416478

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('listarrays')"           # [not win]
    - "\"%R%\" -e \"library('listarrays')\""  # [win]

about:
  home: https://github.com/t-kalinowski/listarrays, https://t-kalinowski.github.io/listarrays/
  license: GPL-3
  summary: A toolbox for R arrays. Flexibly split, bind, reshape, modify,  subset and name arrays.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: listarrays
# Type: Package
# Title: A Toolbox for Working with R Arrays in a Functional Programming Style
# Version: 0.2.0
# Authors@R: person("Tomasz", "Kalinowski", email = "kalinowskit@gmail.com",  role = c("aut", "cre"))
# Description: A toolbox for R arrays. Flexibly split, bind, reshape, modify,  subset and name arrays.
# URL: https://github.com/t-kalinowski/listarrays, https://t-kalinowski.github.io/listarrays/
# BugReports: https://github.com/t-kalinowski/listarrays/issues
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# ByteCompile: true
# RoxygenNote: 6.1.1
# Suggests: testthat, magrittr, zeallot, rlang, tibble, purrr
# NeedsCompilation: no
# Packaged: 2019-03-24 21:26:30 UTC; tomasz
# Author: Tomasz Kalinowski [aut, cre]
# Maintainer: Tomasz Kalinowski <kalinowskit@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-03-24 21:40:02 UTC
