appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: FddN/JsdYeLa5eJjKpsrKGN2z1382U9MRLafkYUcWpod8KBfuRZyfw+wIcv56FPfKhDBjCL+9V9ci0ZO0ky3DeSid5ufzu3ixQ86H+SqVDmNNCdFLsXmfa4okyuiYZA53bkz2aXWeIaij6iCRBXA7aylQ9VdcVqNFnooSznHD/nmmgcs2ayxoUNIDqHK8PcjLtN8JnI1bQSGPUiou/EyFubv8qUUvjZ3iER39V0Awfnfo32a3U4kj5vexqSHZMHIRBr4HHL7asrtNe+s9sfJ0+y8+xMVLR3CuKFRufkFxE0Zo9y/3Q9IjgIm2qLLtieOKwOmhJJmJsUVBz4pGO9SemgWpX1bxRBiAHjCUyN1pH4kODbo79+yRXjhyhxrRUArXger3aPh+LLfyHYGxHImzXk1y04my14cbQKgTIT4nRekseLGfHylMV0ud0OW6oxCktdJ/WoXw4FAQgv3GOAcNqtGjDKqcCdXRWMQJsvJEVo7uf8glf6KcMSCVTJlM2PlX75u47IiBOeNw+aSjuDz8NT34ATQRVFNdH3WBr/ztGP+dxJCT9az4bQ+9jpu9kW2S+viwYj5AbNlSNk/wEEnWECrglAhzBFqFohYHyAF0kLCHEUgKFChBUe63/H1BbKuG9x8gt7xu/uuk1yxVCK2cWYBFD4Fc4yAxp8V/I79cmQ=
conda_forge_output_validation: true
